# Generated by Django 4.0.3 on 2022-03-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('narx', models.CharField(max_length=15)),
                ('miqdor', models.IntegerField()),
                ('brend_nomi', models.CharField(max_length=20)),
                ('omborxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombor.ombor')),
            ],
        ),
    ]
